config/routes.rb
Rails.application.routes.draw do
  root 'pages#search'

  get 'pages/song'
  
  resources :song

end

app/models/song.rb
class Song < ActiveRecord::Base
  def self.search(search)
    if search
      @search = Song.search(params[:search]).order("created_at DESC")
    else
      @search = Song.all.order("created_at DESC")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def song
    client = Grooveshark::Client.new
    song = client.search_songs('@search').first
    url = client.get_song_url(song)
    redirect_to url
  end
  
  def search
    @search = Song.search(params[:search])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/search.html.erb
<center>
    <h1>Music Search</h1>
    <p></p>
    <%= form_tag pages_song_path, :method => "get" do %>
    <div class="search">
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :name => nil %>
    </div>
    <% end %>
    <p></p>
    <p>powered by <a href="http://grooveshark.com/">Grooveshark</a></p>
</center>

app/views/pages/song.html.erb
<center>
    <h1>Music: Song</h1>
    <p><b>Now Playing:</b></p>
    <% get_song_url %>
    <p></p>
    <p>powered by <a href="http://grooveshark.com/">Grooveshark</a></p>
</center>